### ISSUE TITLE
Kappa-Maki doesn't support cucumber dry-run

### ISSUE THREAD

**Issue by Carlbc18** [allantokuda/kappa-maki#2]
I am unable to run `cucumber -d features/*`

The below error is thrown:

```
uninitialized constant Cucumber::Features (NameError)
/Users/john.doe/coolkid/features/step_definitions/cool_kid_steps.rb:1:in `<top (required)>'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_language.rb:94:in `load'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_language.rb:94:in `load_code_file'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb:237:in `load_file'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb:97:in `block in load_files!'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb:96:in `each'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb:96:in `load_files!'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:242:in `load_step_definitions'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:65:in `run!'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/bin/cucumber:23:in `load'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/bin/cucumber:23:in `<main>'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
/Users/john.doe/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by allantokuda** [comment]
Now in 0.0.5, dry-run mode executes without error, but still does not actually prevent the local steps from being executed. It at least allows global steps to be dry-run. I will look into what it will take to make the feature work fully.
